### ISSUE TITLE
createchannel pod Error reading configuration Unsupported Config Type ""

### ISSUE THREAD

**Issue by y0zg** [IBM/blockchain-network-on-kubernetes#55]
Please check this issue during deployment 

**Similar issue found**: https://jira.hyperledger.org/browse/FAB-15582 and refers to variable FABRIC_CFG_PATH

How deployment performed:
`cp setup_blockchainNetwork_v2.sh setup_blockchainNetwork.sh`

`./setup_blockchainNetwork.sh`

Deployment ends with error

```
...
...
Waiting for createchannel job to be completed
Waiting for createchannel job to be completed
Waiting for createchannel job to be completed
Waiting for createchannel job to be completed
Create Channel Failed
```
**K8s version**
```
k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6+IKS", GitCommit:"44b769243cf9b3fe09c1105a4a8749e8ff5f4ba8", GitTreeState:"clean", BuildDate:"2019-08-21T12:48:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

PODs status
```
kubectl get pods                                                    ltop: Fri Sep 27 17:02:13 2019

NAME                                    READY   STATUS      RESTARTS   AGE
blockchain-ca-886988b8b-rxlfz           1/1     Running     0          4m50s
blockchain-orderer-6db47d79c5-mjkhc     1/1     Running     0          4m50s
blockchain-org1peer1-66d79b769c-s922r   1/1     Running     0          4m49s
blockchain-org2peer1-64c85fd696-tfdm5   1/1     Running     0          4m49s
blockchain-org3peer1-75f44fcbcb-wdg8c   1/1     Running     0          4m49s
blockchain-org4peer1-5fbc796dfb-pd4qz   1/1     Running     0          4m49s
copyartifacts-n9sw9                     0/1     Completed   0          5m19s
createchannel-x2hh7                     1/2     Error       0          4m30s
docker-dind-6d74f44c75-84xtt            1/1     Running     0          5m31s
utils-56fd4                             0/2     Completed   0          4m57s
```

Error:

```
k logs -f createchannel-p7fwx createchanneltx 
/shared
bootstrap
keepalived
systemd-private-b1e7ce2665e74f0ba199a5978a3e93de-ntp.service-bZ8Odk
systemd-private-b1e7ce2665e74f0ba199a5978a3e93de-systemd-resolved.service-5oUCv1
2019-09-27 15:29:53.338 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
2019-09-27 15:29:53.338 UTC [common.tools.configtxgen.localconfig] Load -> PANI 002 Error reading configuration:  Unsupported Config Type ""
2019-09-27 15:29:53.338 UTC [common.tools.configtxgen] func1 -> PANI 003 Error reading configuration:  Unsupported Config Type ""
panic: Error reading configuration:  Unsupported Config Type "" [recovered]
	panic: Error reading configuration:  Unsupported Config Type ""

goroutine 1 [running]:
github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00011bc30, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000ac240, 0xc0001a3804, 0xc0000f0d00, 0x38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc0000ac240, 0xc0000f0d00, 0x38, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000ac248, 0xc0001a3908, 0x1, 0x1)
	/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x75
main.main.func1()
	/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:260 +0x1a9
panic(0xd62c40, 0xc00009f9c0)
	/opt/go/src/runtime/panic.go:513 +0x1b9
github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00011bc30, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/zapcore/entry.go:229 +0x515
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).log(0xc0000ac220, 0xc0001a3c04, 0xc0000f0c00, 0x38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:234 +0xf6
github.com/hyperledger/fabric/vendor/go.uber.org/zap.(*SugaredLogger).Panicf(0xc0000ac220, 0xc0000f0c00, 0x38, 0x0, 0x0, 0x0)
	/opt/gopath/src/github.com/hyperledger/fabric/vendor/go.uber.org/zap/sugar.go:159 +0x79
github.com/hyperledger/fabric/common/flogging.(*FabricLogger).Panic(0xc0000ac228, 0xc0001a3d88, 0x2, 0x2)
	/opt/gopath/src/github.com/hyperledger/fabric/common/flogging/zap.go:73 +0x75
github.com/hyperledger/fabric/common/tools/configtxgen/localconfig.Load(0x7ffe691e4f6b, 0xf, 0x0, 0x0, 0x0, 0xc00018b9e0)
	/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/localconfig/config.go:276 +0x41f
main.main()
	/opt/gopath/src/github.com/hyperledger/fabric/common/tools/configtxgen/main.go:271 +0xce0

```

```
peer chaincode query -C channel1 -n cc -c '{"Args":["query","a"]}'^C
...
...
2019-09-27 14:00:21.689 UTC [msp] Validate -> DEBU 035 MSP Org1MSP validating identity
2019-09-27 14:00:21.690 UTC [grpc] DialContext -> DEBU 036 parsed scheme: ""
2019-09-27 14:00:21.690 UTC [grpc] DialContext -> DEBU 037 scheme "" not registered, fallback to default scheme
2019-09-27 14:00:21.690 UTC [grpc] watcher -> DEBU 038 ccResolverWrapper: sending new addresses to cc: [{blockchain-org1peer1:30110 0  <nil>}]
2019-09-27 14:00:21.690 UTC [grpc] switchBalancer -> DEBU 039 ClientConn switching balancer to "pick_first"
2019-09-27 14:00:21.690 UTC [grpc] HandleSubConnStateChange -> DEBU 03a pickfirstBalancer: HandleSubConnStateChange: 0xc0003f2630, CONNECTING
2019-09-27 14:00:21.695 UTC [grpc] HandleSubConnStateChange -> DEBU 03b pickfirstBalancer: HandleSubConnStateChange: 0xc0003f2630, READY
2019-09-27 14:00:21.695 UTC [grpc] DialContext -> DEBU 03c parsed scheme: ""
2019-09-27 14:00:21.695 UTC [grpc] DialContext -> DEBU 03d scheme "" not registered, fallback to default scheme
2019-09-27 14:00:21.696 UTC [grpc] watcher -> DEBU 03e ccResolverWrapper: sending new addresses to cc: [{blockchain-org1peer1:30110 0  <nil>}]
2019-09-27 14:00:21.696 UTC [grpc] switchBalancer -> DEBU 03f ClientConn switching balancer to "pick_first"
2019-09-27 14:00:21.696 UTC [grpc] HandleSubConnStateChange -> DEBU 040 pickfirstBalancer: HandleSubConnStateChange: 0xc000455eb0, CONNECTING
2019-09-27 14:00:21.700 UTC [grpc] HandleSubConnStateChange -> DEBU 041 pickfirstBalancer: HandleSubConnStateChange: 0xc000455eb0, READY
2019-09-27 14:00:21.704 UTC [msp] GetDefaultSigningIdentity -> DEBU 042 Obtaining default signing identity
2019-09-27 14:00:21.705 UTC [msp.identity] Sign -> DEBU 043 Sign: plaintext: 0AA4070A6408031A0C08F5ABB8EC0510...120263631A0A0A0571756572790A0161 
2019-09-27 14:00:21.705 UTC [msp.identity] Sign -> DEBU 044 Sign: digest: CE7327A88C6BEF47C34483617ACF351E9BFAE295DB3D70F744B71EFD8A670D0F 
Error: error endorsing query: rpc error: code = Unknown desc = access denied: channel [channel1] creator org [Org1MSP] - proposal response: <nil>

```

**Comment by y0zg** [comment]
@kant , @maheshwarishikha  , 
Could you please have a look into this?

**Comment by maheshwarishikha** [comment]
@y0zg , Please check https://github.com/IBM/blockchain-network-on-kubernetes/issues/54 - if it helps.

**Comment by y0zg** [comment]
Thanks @maheshwarishikha , this helped.

Do you know what might be the root cause if setup hangs with message "Waiting for copyartifacts job to complete"?

**Comment by maheshwarishikha** [comment]
Hi @y0zg ,  if setup hangs with message "Waiting for copyartifacts job to complete" - it is mostly intermittent issue...with any reson say network or something else. Retrial solves that.

**Comment by maheshwarishikha** [comment]
Closing this issue, as it worked for you. Feel free to reopen or open a new issue if required. Thanks.
